CREATE TABLE IF NOT EXISTS propertystorage (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    path VARBINARY(1024) NOT NULL,
    name VARBINARY(100) NOT NULL,
    valuetype INT UNSIGNED,
    value MEDIUMBLOB,
    UNIQUE path_property (path(600), name(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
